import path from 'path';

export default [
  {
    path: '/',
    includeInGatsby: true,
    title: 'home',
    key: 'home',
    component: path.resolve('src/main-pages/Home/index.js'),
  },
  {
    path: '/home',
    includeInGatsby: true,
    title: 'home',
    key: 'home',
    component: path.resolve('src/main-pages/Home/index.js'),
  },
  {
    title: 'news',
    isMain: true,
    path: '/news',
    key: 'news',
    component: path.resolve('src/main-pages/News/index.js'),
    translationKey: 'news',
  },
  {
    title: 'Music Sheet Scores',
    isMain: true,
    key: 'scores',
    path: '/music-sheet-scores',
    component: path.resolve('src/main-pages/Scores/index.js'),
    translationKey: 'scores.title',
    pageDescriptionTranslationKey: 'scores.description',
  },
  {
    key: 'musicians',
    title: 'musicians',
    isMain: true,
    path: '/musicians',
    translationKey: 'musicians',
    component: path.resolve('src/main-pages/Musicians/index.js'),
  },
  {
    title: 'About Us',
    path: '/about-us',
    key: 'aboutUs',
    includeInGatsby: true,
    component: path.resolve('src/main-pages/AboutUs/index.js'),
    translationKey: 'aboutUs',
    pageDescriptionTranslationKey: 'aboutUs.info',
  },
  {
    title: 'Contact Us',
    isMain: true,
    path: '/contact-us',
    key: 'contactUs',
    component: path.resolve('src/main-pages/ContactUs/index.js'),
    translationKey: 'contactUs',
  },
  {
    key: 'terms',
    includeInGatsby: true,
    title: 'terms',
    path: '/terms',
    translationKey: 'termsAndPrivacyPolicy',
    component: path.resolve('src/main-pages/Terms/index.js'),
  },
  {
    includeInGatsby: true,
    key: 'profile',
    title: 'User Profile',
    path: '/user-profile',
    translationKey: 'profile',
    component: path.resolve('src/main-pages/UserProfile/index.js'),
  },
  {
    includeInGatsby: true,
    key: 'signIn',
    title: 'Sign In',
    path: '/auth/sign-in',
    component: path.resolve('src/Auth/AuthFormWrapper/index.js'),
  },
  {
    includeInGatsby: true,
    key: 'signUp',
    title: 'Sign Up',
    path: '/auth/sign-up',
    component: path.resolve('src/Auth/AuthFormWrapper/index.js'),
  },
  {
    includeInGatsby: true,
    key: 'resetPassword',
    title: 'Reset Password',
    path: '/reset-password/:token',
    component: path.resolve('src/Auth/ResetPassword/index.js'),
  },
];
