export default {
  hy: {
    weekdays: [
      'Կիրակի',
      'Երկուշաբթի',
      'Երեքշաբտի',
      'Չորեքշաբթի',
      'Հինգշաբթի',
      'Ուրբաթ',
      'Շաբաթ',
    ],
    weekDaysShort: [
      'Կիր',
      'Erk',
      'Երք',
      'Չոր',
      'Հնգ',
      'Ուրբ',
      'Շաբ',
    ],
    months: [
      'Հունվար',
      'Փետրվար',
      'Մարտ',
      'Ապրիլ',
      'Մայիս',
      'Հունիս',
      'Հուլիս',
      'Օգօստոս',
      'Սեպտեմբեր',
      'Հոկտեմբեր',
      'Նոյեմբեր',
      'Դեկտեմբեր',
    ],
    monthsShort: [
      'Հնվ',
      'Փտվ',
      'Մրտ',
      'Ապր',
      'Մյս',
      'Հնս',
      'Հլս',
      'Օգս',
      'Սպտ',
      'Հկտ',
      'Նյմ',
      'Դկտ',
    ],
  },
  en: {
    dayNames: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    dayNamesShort: [
      'Sun',
      'Mon',
      'Tue',
      'Wed',
      'Thu',
      'Fri',
      'Sat',
    ],
    monthNames: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    monthNamesShort: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],
  },
};
