name: Docker Build

on:
  push:
    branches: ["stage", "prod"]
    paths:
      - .github/workflows/build.yml
      - "packages/**"
      - package.json
      - yarn.lock
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: whoan/docker-build-with-cache-action@v4
        with:
          username: tigrankeshishyan
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: tigrankeshishyan/anm-web/server
          image_tag: latest
          registry: docker.pkg.github.com

      - name: curl ${{ secrets.DEPLOY_WEBHOOK }}
