name: Docker Build

on:
  push:
    branches: ["stage", "prod"]
    paths:
      - .github/workflows/build.yml
      - "packages/**"
      - package.json
      - yarn.lock
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: tigrankeshishyan/anm-web/server
          image_tag: latest
          registry: docker.pkg.github.com

      - name: Create ssh keys from SECRETS
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.rsa }}" > ~/.ssh/id_rsa
          echo "${{ secrets.rsa_pub }}" > ~/.ssh/id_rsa.pub
          chmod 400 ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa.pub
      - run: ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: deploy server
        run: >-
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER }}
          'docker pull docker.pkg.github.com/tigrankeshishyan/anm-web/server:latest; docker service update ${{ secrets.DOCKER_SERVICE }} --force'
