name: deploy client

on:
  push:
    branches: ['dev', 'prod']
    paths: 
      - packages/client/**
      - package.json
      - .github/workflows/deploy-client.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create ssh keys from SECRETS
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.GITHUB_RSA }}" > ~/.ssh/id_rsa
        echo "${{ secrets.GITHUB_RSA_PUBLIC }}" > ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa.pub

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - run: ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: build client
      run: >-
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER }}
        'cd ~/${{steps.extract_branch.outputs.branch}}/;
        ANM_ENV=${{steps.extract_branch.outputs.branch}} yarn client build'
        
      
