name: deploy client

on:
  push:
    branches: ['stage', 'prod']
    paths: 
      - packages/client

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create ssh keys from SECRETS
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.GITHUB_RSA }}" > ~/.ssh/id_rsa
        echo "${{ secrets.GITHUB_RSA_PUBLIC }}" > ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa.pub

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    
    - uses: actions/checkout@v1
      with:
        ref: ${{steps.extract_branch.outputs.branch}}
        
        
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - run: yarn client install
    - name: Build with 
      run: yarn client build-${{ steps.extract_branch.outputs.branch }}
      
    - name: deploy client
      env:
        ANM_ENV: ${{steps.extract_branch.outputs.branch}}
      run: yarn sync      
